# Generated by Django 4.1.7 on 2023-03-01 13:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("memogenerator", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="pitch",
        ),
        migrations.AddField(
            model_name="company",
            name="emailTo",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="pitch_uploaded",
            field=models.FileField(blank=True, null=True, upload_to="mediafiles/"),
        ),
    ]
