# Generated by Django 4.1.7 on 2023-03-03 09:45

from django.db import migrations, models
import memogenerator.models


class Migration(migrations.Migration):

    dependencies = [
        ('memogenerator', '0002_remove_company_pitch_company_emailto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='pitch_uploaded',
            field=models.FileField(blank=True, null=True, upload_to=memogenerator.models.upload_to),
        ),
    ]
